name: tugas2teori
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  geolocator: ^10.0.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  google_nav_bar: ^5.0.7
  go_router: ^15.0.0
  provider: ^6.1.4
  url_launcher: ^6.3.1
  webview_flutter: ^4.4.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/
  uses-material-design: true

  